[phases.setup]
nixPkgs = ['nodejs', 'postgresql']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
    'cd server && npx prisma generate',
    'cd client && npm install && npm run build',
    'cd server && npm install && npm run build'
]

[start]
cmd = 'cd server && npm start'
