[phases.setup]
nixPkgs = ['nodejs', 'postgresql']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
    'cd client && npm install && npm run build',
    'cd server && npx prisma generate && npm install && npm run build'
]

[start]
cmd = 'cd server && NODE_ENV=production npm start'

[start.environment]
PORT = "3000"
NODE_ENV = "production"
